spring.application.name=core-service
server.port=8082

# =======================
# DATABASE CONFIG (PostgreSQL)
# =======================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/secondhand_core_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================
# JPA / HIBERNATE
# =======================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false

management.endpoints.web.exposure.include=health,info

# =======================
# JWT CONFIG
# =======================
jwt.secret=SECONDHAND_SECRET_KEY_2026_CHANGE_ME
jwt.expiration-ms=86400000
# Debug security (r?t h?u �ch khi test JWT)
logging.level.org.springframework.security=DEBUG

# =======================
# CLOUDINARY CONFIG
# =======================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dgachkyc7}
cloudinary.api-key=${CLOUDINARY_API_KEY:421262947271889}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:2YJG_3cmYpWjGX7BW3q598wWQ3g}
cloudinary.folder=secondhand-items

# =======================
# AUTH SERVICE CONFIG (Feign Client via Kong or direct)
# =======================
# Local (IntelliJ): http://localhost:8000/auth  (qua Kong chạy Docker)
# Docker (full Docker): http://kong:8000/auth
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8000/auth}
# =======================
# INTERNAL SERVICE URLs
# =======================
order.service.url=${ORDER_SERVICE_URL:http://localhost:8083}

# =======================
# REDIS / CACHE
# =======================
spring.cache.type=redis
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# =======================
# RABBITMQ
# =======================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin123}
