spring.application.name=chat-service
server.port=8084

# =========================
# MONGODB
# =========================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27019/secondhand_chat_db}
spring.data.mongodb.auto-index-creation=true

# =========================
# REDIS
# =========================
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin123}

# =========================
# JWT
# =========================
jwt.secret=SECONDHAND_SECRET_KEY_2026_CHANGE_ME
jwt.expiration-ms=86400000

logging.level.org.springframework.security=DEBUG

# =========================
# SPRING DEVTOOLS (hot reload)
# =========================
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s